### ISSUE TITLE
ImportError: cannot import name 'HF_MODEL_NAME' from 'comfyui_controlnet_aux.utils'

### ISSUE THREAD

**Issue by sgsrules** [shockz0rz/ComfyUI_InterpolateEverything#3]
Interpolate everything fails to import. I have control net aux installed.  I've tried installing both control net aux and interpolate everything via comyfui manager as well as pulling them directly using git.

Traceback (most recent call last):
  File "F:\CodeProjects\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\CodeProjects\ComfyUI\custom_nodes\ComfyUI_InterpolateEverything\__init__.py", line 22, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\CodeProjects\ComfyUI\custom_nodes\ComfyUI_InterpolateEverything\nodes.py", line 5, in <module>
    from comfyui_controlnet_aux.utils import common_annotator_call, annotator_ckpts_path, HF_MODEL_NAME
ImportError: cannot import name 'HF_MODEL_NAME' from 'comfyui_controlnet_aux.utils' (F:\CodeProjects\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py)

Cannot import F:\CodeProjects\ComfyUI\custom_nodes\ComfyUI_InterpolateEverything module for custom nodes: cannot import name 'HF_MODEL_NAME' from 'comfyui_controlnet_aux.utils' (F:\CodeProjects\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py)

**Comment by dominikbenk** [comment]
Same problem.

**Comment by dominikbenk** [comment]
Fixed by adding `HF_MODEL_NAME = "lllyasviel/Annotators"` to ComfyUI/custom_nodes/comfyui_controlnet_aux/utils.py Apparently, this was removed in [this version](https://github.com/Fannovel16/comfyui_controlnet_aux/commit/9a8deeb79f7d799606c3b47e22103357172340e7) of the auxiliary plugin.

**Comment by sgsrules** [comment]
thanks for the update, that indeed fixed it, but this will probably get
broken next time controlnet_aux is updated.  You might want to add this
comment to the github thread so others can see it.

Cheers!

**Comment by proteus2000** [comment]
i have the same issue. everything updated to latest version, but still same error message

**Comment by spelafort** [comment]
Same issue still. Any fix?

**Comment by spelafort** [comment]
Where do you add this line? I added it and now interpolateeverything shows up in the nodes list, but doesn't work. I get the following error:

```Error occurred when executing OpenposePreprocessorInterpolate:

OpenposeDetector.from_pretrained() got an unexpected keyword argument 'cache_dir'

```
